// Discover hosts doing possible network scans
let remotePortCountThreshold = 10; // Please change the min value, for a host reaching out to remote ports on a remote IP, that you consider to be threshold for a suspicious behavior 
DeviceNetworkEvents
| where Timestamp > ago(1d) and RemoteIP startswith "172.16" or RemoteIP startswith "192.168" 
| summarize
    by DeviceName, RemoteIP, RemotePort, InitiatingProcessFileName
| summarize RemotePortCount=dcount(RemotePort) by DeviceName, RemoteIP, InitiatingProcessFileName
| where RemotePortCount > remotePortCountThreshold
